Tly 12 appointments
TymekSzczepkowski/Teachly-Frontend pull request #3
Opened 2022-07-25 09:54 UTC by TymekSzczepkowski

2022-07-25 14:52 UTC, Jertusz requested changes
Other than submitted comments, the tests are only testing success paths without taking into account any 400 errors. Those cases should be covered too.

2022-07-25 14:52 UTC, Jertusz commented on teachly-frontend/src/components/LessonPage/AvailabilityCalendar.js
> +                      {!auth ? <ListItemText primary={`Zaloguj się`} secondary={`Musisz być zalogowany, aby zobaczyć dostępność korepetytora`} /> : <ListItemText primary={`Brak zajęć`} secondary={`Te
Typo: nauczciel -> nauczyciel

2022-07-25 14:52 UTC, Jertusz commented on teachly-frontend/src/components/LessonPage/AvailabilityCalendar.js
> +            <Typography varinat='h6' sx={{ fontWeight: 500, pl: { xs: 2 } }}>
Typo: varinat -> variant

2022-07-25 14:52 UTC, Jertusz commented on teachly-frontend/src/components/LessonPage/OtherOffers.js
> +      id={"teacher-feedback-button"}
Misleading id, those are other offers, not feedback

2022-07-25 14:52 UTC, Jertusz commented on teachly-frontend/src/components/LessonPage/Utils/TeacherDetails.js
>  function TeacherDetails({ offerDetails }) {
I think we're passing to broad information here, just the teacher details should be passed to the component instead of the whole listing object.

2022-07-25 14:52 UTC, Jertusz commented on teachly-frontend/src/components/MyAccount/Scheduler/Actions/AddHours.js
> +  const dayOffDate = date.toLocaleDateString("sv-SE"); //daysoff
Comments aren't bringing any value here, variable names are verbose enough

2022-07-25 14:52 UTC, Jertusz commented on teachly-frontend/src/components/MyAccount/Scheduler/Actions/AddHours.js
> +          setAlertMessage({ ...alertMessage, isSuccess: true, severity: "success", message: "Nowa dzień wolny dadano pomyślnie" });
Typo: Nowa -> nowy
Typo: dadano -> dodano

2022-07-25 14:52 UTC, Jertusz commented on teachly-frontend/src/components/MyAccount/Scheduler/Actions/AddHours.js
> +            </React.Fragment>
Instead of React.Fragment use <></>, that's the new syntax for fragments
Ref: https://reactjs.org/docs/fragments.html#short-syntax

2022-07-25 14:52 UTC, Jertusz commented on teachly-frontend/src/components/MyAccount/Scheduler/Actions/EditHours.js
> +            </React.Fragment>
React.Fragment -> <>
Ref: https://reactjs.org/docs/fragments.html#short-syntax

2022-07-25 14:52 UTC, Jertusz commented on teachly-frontend/src/components/MyAccount/Scheduler/CustomWorkingHours/CustomWorkingHours.js
> +        month === date.getMonth() + 1 ? setDaysToHighlight(daysWithCustomHours[0].map((e) => parseInt(e.substr(8, 2))).filter((day) => day >= new Date().getUTCDate())) : setDaysToHighlight(daysWithCu
Can't we use date.getUTCDate() here instead of creating a new objects for each day?

2022-07-25 14:52 UTC, Jertusz commented on teachly-frontend/src/components/MyAccount/Scheduler/DaysOff/DaysOff.js
> +        month === date.getMonth() + 1 ? setDaysToHighlight(daysWithDaysOff.map((e) => parseInt(e.substr(8, 2))).filter((day) => day >= new Date().getUTCDate())) : setDaysToHighlight(daysWithDaysOff.m
Can't we use date.getUTCDate() here instead of creating a new objects for each day?

2022-07-25 14:52 UTC, Jertusz commented on teachly-frontend/src/components/MyAccount/Scheduler/DaysOff/DaysOff.js
> +  const [daysOffDays, setDaysOffDays] = useState();
Rename to more verbose: daysOffDays -> daysOff or if those are supposed to be new days off, then newDaysOff.

2022-07-25 14:52 UTC, Jertusz commented on teachly-frontend/src/components/MyAccount/Scheduler/Scheduler.js
> +  }, [selectedDate]);
Remove temp variables or change name to be more verbose.

2022-07-25 14:52 UTC, Jertusz commented on teachly-frontend/src/pages/Auth/Register/Register.js
>        if (validateProfileType(profileTypeSelection) === "" && validateEmail(state.email) === "" && validatePassword(state.password) === "" && validateRepeatInput(state.password, state.repeatPassword)
Not sure why are we comparing validates to "", the functions return a Boolean value which can be checked like this: `
if (validateProfileType()){
  do when true
} else {
  do when false
}`

2022-07-25 14:52 UTC, Jertusz commented on teachly-frontend/src/pages/MyAccount/MyAccount.js
> +            </Typography> */}
Unnecessary comments?

2022-07-25 14:52 UTC, Jertusz commented on teachly-test/test/specs/Availability/customdays.js
> +describe("Testing avaliability in custom hours calendar", () => {
Typo: avaliability -> availability

2022-07-25 14:52 UTC, Jertusz commented on teachly-test/test/specs/Availability/daysoff.js
> +describe("Testing avaliability in days off calendar", () => {
Typo: avaliability -> availability

2022-07-25 14:52 UTC, Jertusz commented on teachly-test/test/specs/Availability/regulardays.js
> +describe("Testing avaliability in regular hours calendar", () => {
Typo: avaliability -> availability

2022-07-25 16:31 UTC, TymekSzczepkowski commented on teachly-frontend/src/pages/MyAccount/MyAccount.js
> +            </Typography> */}
no :)

2022-07-25 16:39 UTC, TymekSzczepkowski commented on teachly-frontend/src/pages/Auth/Register/Register.js
>        if (validateProfileType(profileTypeSelection) === "" && validateEmail(state.email) === "" && validatePassword(state.password) === "" && validateRepeatInput(state.password, state.repeatPassword)
Each error returns a different message, considering it true / false will not solve the problem.

2022-07-26 11:02 UTC, TymekSzczepkowski commented on teachly-frontend/src/components/MyAccount/Scheduler/Actions/EditHours.js
> +            </React.Fragment>
If we use maps every element must have a key prop and we can't add it without React.Fragment.

2022-07-26 15:05 UTC, Jertusz requested changes

2022-07-26 15:05 UTC, Jertusz commented on teachly-frontend/src/components/MyAccount/Scheduler/Actions/AddHours.js
> +          setAlertMessage({ ...alertMessage, isSuccess: true, severity: "success", message: "Nowy dzień wolny dadany pomyślnie" });
Typo: dadany -> dodany

2022-07-26 15:25 UTC, Jertusz approved these changes

2022-07-26 15:25 UTC, merged